//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerGuidance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Authority
    {
        public string Authorization { get; set; }
    
        public virtual User_Role User_Role { get; set; }
    }
}
